# .zprofile
# We'll set the environemnt variables here

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Ensure user-installed binaries take precedence (homebrew, specifically)
PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Gnu coreutils take precedence
PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
# And Gnu coreutils manuals
export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"

# Virtualenvwrapper
export WORKON_HOME=$HOME/Programmazione/VirtualEnvs
export PROJECT_HOME=$HOME/Programmazione
source /usr/local/bin/virtualenvwrapper_lazy.sh

# Android SDK
PATH="/opt/adt-bundle-mac-x86_64/sdk/tools:/opt/adt-bundle-mac-x86_64/sdk/platform-tools:$PATH"

# Go
export GOPATH=$HOME/Programmazione/Go
PATH="/usr/local/opt/go/libexec/bin:$GOPATH/bin:$PATH"

# Java
export LANG=en_US.UTF-8
export JAVA_HOME=$(/usr/libexec/java_home)

# OPAM configuration
. /Users/aldur/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# RubyGems environment.
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

# NodeJS / NVM
export NVM_DIR="/Users/aldur/.nvm"
. $(brew --prefix nvm)/nvm.sh

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ]; then
    PATH="$HOME/.bin":$PATH
fi

# Load Python RC file
export PYTHONSTARTUP="$HOME/.pythonrc"

export PATH=$PATH
