# .zprofile
# We'll set the environemnt variables here
# Ensure user-installed binaries take precedence (homebrew, specifically)
PATH="/usr/local/bin:/usr/local/sbin/:$PATH"

# Gnu coreutils take precedence
PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
# And Gnu coreutils manuals
export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"

# Virtualenvwrapper
export WORKON_HOME=$HOME/Programmazione/VirtualEnvs
export PROJECT_HOME=$HOME/Programmazione
source /usr/local/bin/virtualenvwrapper.sh

# Android SDK
PATH="/opt/adt-bundle-mac-x86_64/sdk/tools:/opt/adt-bundle-mac-x86_64/sdk/platform-tools:$PATH"

# Go
export GOPATH=$HOME/Programmazione/Go
PATH="/usr/local/opt/go/libexec/bin:$GOPATH/bin:$PATH"

# Java
export LANG=en_US.UTF-8
export JAVA_HOME=$(/usr/libexec/java_home)

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ]; then
    PATH="$HOME/.bin:$PATH"
fi

export PATH=$PATH
