# Uncommet this line to load `zprof`
# zmodload zsh/zprof

# -=- ZSH-specific options -=-
setopt PROMPT_SUBST  # Enable substitutions in prompt.
setopt INTERACTIVE_COMMENTS  # Enable # comments in interactive mode

setopt AUTO_CD
setopt AUTO_PUSHD
setopt CHASE_LINKS

setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

# Completion
setopt ALWAYS_TO_END
setopt AUTO_MENU
setopt AUTO_PARAM_SLASH
setopt COMPLETE_ALIASES
setopt COMPLETE_IN_WORD
setopt NO_CASE_GLOB

setopt BAD_PATTERN

# History configuration.
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt SHARE_HISTORY
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE

setopt CORRECT
setopt CORRECT_ALL

# Disable bells (iTerm disables them, but the `nvim` terminal does not)
unsetopt BEEP

[ -f $HOME/.dotfiles/zsh/aldur.zsh-theme ] && source $HOME/.dotfiles/zsh/aldur.zsh-theme

# Man Syntax Highlightning
export LESS_TERMCAP_mb=$(printf "\e[1;31m")
export LESS_TERMCAP_md=$(printf "\e[1;31m")
export LESS_TERMCAP_me=$(printf "\e[0m")
export LESS_TERMCAP_se=$(printf "\e[0m")
export LESS_TERMCAP_so=$(printf "\e[1;44;33m")
export LESS_TERMCAP_ue=$(printf "\e[0m")
export LESS_TERMCAP_us=$(printf "\e[1;32m")

# Completion
zmodload -i zsh/complist
bindkey -M menuselect '\e' send-break  # Esc to cancel completion
bindkey -M menuselect '^[[Z' reverse-menu-complete  # shift-tab to go back

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]} r:|[._-]=** r:|=**'
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' special-dirs true  # Complete . and .. special directories

autoload -Uz compinit

# The globbing is a little complicated here:
# - '#q' is an explicit glob qualifier that makes globbing work within zsh's [[ ]] construct.
# - 'N' makes the glob pattern evaluate to nothing when it doesn't match (rather than throw a globbing error)
# - '.' matches "regular files"
# - 'mh+24' matches files (or directories or whatever) that are older than 24 hours.
# Note that we are setting `EXTENDED_GLOB` otherwise this would not match.
setopt EXTENDED_GLOB
if [[ -n $HOME/.zcompdump(#qN.mh+24) ]]; then
  compinit
  touch .zcompdump
else
  compinit -C
fi
unsetopt EXTENDED_GLOB

# VIM keybindings
export KEYTIMEOUT=5
[ -f $HOME/.dotfiles/zsh/zsh-vim-mode/zsh-vim-mode.plugin.zsh ] && source $HOME/.dotfiles/zsh/zsh-vim-mode/zsh-vim-mode.plugin.zsh

# Disable annoying `execute-named-cmd`
bindkey -M vicmd -r :

MODE_INDICATOR_VICMD='%F{2}%B[NORMAL]%f%b'
MODE_INDICATOR_REPLACE='%F{1}%B[REPLACE]%f%b'
MODE_INDICATOR_SEARCH='%F{5}%B[SEARCH]%f%b'
MODE_INDICATOR_VISUAL='%F{4}%B[VISUAL]%f%b'
MODE_INDICATOR_VLINE='%F{4}%B[V-LINE]%f%b'

# ----------- Personal configuration -------------

# Aliases
alias history='fc -dElD 0'  # Better history with timestamps, elapsed time, etc.

# Git aliases
alias gst='git status'
alias gc='git commit'
alias gd='git diff'
alias gp='git push'

alias ll='ls -al'

# Colored LS (from `oh-my-zsh`)
[[ -n "$LS_COLORS" || -f "$HOME/.dircolors" ]] && gls --color -d . &>/dev/null && alias ls='gls --color=tty'

# Load local configuration files
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
