# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="aldur"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="dd/mm/yyyy"

plugins=( \
    git \ 
    virtualenv \  # Auto-completion
    brew \ 
    colored-man \  # Colors
    zsh-syntax-highlighting \  # Spellchecking
    history-substring-search z \  # Utilities
)

source $ZSH/oh-my-zsh.sh
# ----------- Personal configuration -------------

# Aliases
# Enable aliases to be sudo’ed
alias sudo='sudo '

# Global environment
# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR=vim
else
    export EDITOR=vim
fi
export VISUAL="$EDITOR"

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# SSH key path
export SSH_KEY_PATH="$HOME/.ssh/id_rsa"

# ZSH specific configuration
# Allows you to type Bash style comments on your command line
# good ol' Bash :)
setopt interactivecomments

# Appends every command to the history file once it is executed
# and reloads the history whenever you use it
setopt inc_append_history
setopt share_history

# Load local configuration files
if [[ -f $HOME/.zshrc.local ]]; then
    source $HOME/.zshrc.local
fi
